import type { PharmacyItem } from "@/types/pharmacy";

export const DEFAULT_PHARMACY_ITEMS: PharmacyItem[] = [
  {
    id: "ph-1",
    name: "PRP Набори для плазмоліфтингу (Autologous PRP)",
    active_substance: "Аутологічна тромбоцитарна плазма",
    category: "injections",
    stock_count: 14,
    unit: "наборів",
    min_alert_threshold: 5,
    expiry_date: "2027-08-30",
    wada_status: "allowed",
    storage_location: "Холодильник медкабінету (+4°C)",
    notes: "Для лікування ентезопатій та надривів м'язів під контролем УЗД",
  },
  {
    id: "ph-2",
    name: "Кінезіотейп K-Active Pro (Чорний / Синій)",
    active_substance: "100% бавовна з гіпоалергенним клеєм",
    category: "tapes_bandages",
    stock_count: 28,
    unit: "рулонів",
    min_alert_threshold: 10,
    expiry_date: "2028-12-31",
    wada_status: "allowed",
    storage_location: "Шафа роздягальні / Виїзна валіза",
    notes: "Водостійкий тейп для лімфодренажу та стабілізації суглобів",
  },
  {
    id: "ph-3",
    name: "Німесулід (Німесил) 100 мг",
    active_substance: "Німесулід",
    category: "nsaid_painkillers",
    stock_count: 65,
    unit: "пакетиків",
    min_alert_threshold: 20,
    expiry_date: "2027-04-15",
    wada_status: "allowed",
    storage_location: "Аптечка медкабінету",
    notes: "Селективний НПЗЗ для короткочасного купірування гострого болю",
  },
  {
    id: "ph-4",
    name: "Дексаметазон 4 мг/мл",
    active_substance: "Дексаметазону фосфат",
    category: "injections",
    stock_count: 18,
    unit: "ампул",
    min_alert_threshold: 6,
    expiry_date: "2026-11-20",
    wada_status: "prohibited_in_competition",
    storage_location: "Сейф суворої звітності",
    notes: "Глюкокортикоїд. Заборонено у змагальний період (S9). Потребує TUE або період виведення > 7 днів!",
  },
  {
    id: "ph-5",
    name: "Гіалуронова кислота 2.0% (Остеніл / Ферматрон)",
    active_substance: "Натрію гіалуронат",
    category: "injections",
    stock_count: 8,
    unit: "шприців",
    min_alert_threshold: 3,
    expiry_date: "2027-10-10",
    wada_status: "allowed",
    storage_location: "Медкабінет база",
    notes: "Внутрішньосуглобовий хондропротектор для захисту хряща коліна",
  },
  {
    id: "ph-6",
    name: "Спортивний заморожувальний спрей (Cryo Ice Spray 400ml)",
    active_substance: "Пропан-бутанова охолоджувальна суміш",
    category: "emergency_antiseptics",
    stock_count: 16,
    unit: "балонів",
    min_alert_threshold: 6,
    expiry_date: "2028-05-01",
    wada_status: "allowed",
    storage_location: "Виїзна валіза матчу",
    notes: "Експрес-знеболення при ударах на футбольному полі",
  },
  {
    id: "ph-7",
    name: "Колаген Peptan + Вітамін C порошок",
    active_substance: "Гідролізат колагену I та III типу",
    category: "vitamins_supplements",
    stock_count: 24,
    unit: "банок",
    min_alert_threshold: 8,
    expiry_date: "2027-09-30",
    wada_status: "allowed",
    storage_location: "Нутриціологічний склад",
    notes: "Приймати за 45 хв до навантаження для прискорення ремоделювання сухожилків",
  },
  {
    id: "ph-8",
    name: "Траумель С розчин для ін'єкцій",
    active_substance: "Комплексний гомеопатичний протизапальний засіб",
    category: "injections",
    stock_count: 30,
    unit: "ампул",
    min_alert_threshold: 10,
    expiry_date: "2027-12-15",
    wada_status: "allowed",
    storage_location: "Медкабінет база",
    notes: "Періартикулярне введення при міозитах та тендинітах",
  },
];
